# Generated by Django 5.1.4 on 2026-06-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('rack_id', models.IntegerField(default=0)),
                ('retail_price', models.DecimalField(decimal_places=5, max_digits=8)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('geocoded', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'stations_gasstation',
                'indexes': [models.Index(fields=['state'], name='stations_ga_state_8bc894_idx'), models.Index(fields=['lat', 'lon'], name='stations_ga_lat_f779a8_idx')],
            },
        ),
    ]
